depth = 5
population_size = 200
min_iterations = 10
thresh = 0.1
iterations = 100
threads = 10
GIFS = True
GIFS_PATH = "data/baseline_results/CMAESGP/GIFS/depth3"
RESULTS_PATH="data/baseline_results/CMAESGP/RESULTS/depth3"