depth = 5
population_size = 200
exploration = 0.1
min_iterations = 10
thresh = 0.1
iterations = 100
threads = 10
GIFS = True
GIFS_PATH = "data/baseline_results/CMAESSemantic/GIFS/depth5"
RESULTS_PATH="data/baseline_results/CMAESSemantic/RESULTS/depth5"